### ISSUE TITLE
Cannot synthesize weak property because the current deployment target does not support weak references

### ISSUE THREAD

**Issue by xiXinStudio** [cityleaf/LYPaymentField#3]
pod 安装提示
Cannot synthesize weak property because the current deployment target does not support weak references

**Comment by cityleaf** [comment]
你好，解决了吗？有两种办法可以试试
1、项目->TARGETS->IOS->Build Settings->Apple Clang - Language - Objective C->WeakReferences inManual Retain Release改为YES
2、将下面这一段粘贴在podfile文件的结尾
`post_install do |installer|  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'StreamingKit'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '7.0'
      end
    end
  end
end`

**Comment by cityleaf** [comment]
> pod 安装提示
> Cannot synthesize weak property because the current deployment target does not support weak references

你好，解决了吗？有两种办法可以试试
1、项目->TARGETS->IOS->Build Settings->Apple Clang - Language - Objective C->WeakReferences inManual Retain Release改为YES
2、将下面这一段粘贴在podfile文件的结尾
post_install do |installer|  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'LYPaymentField'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '7.0'
      end
    end
  end
end

**Comment by cityleaf** [comment]
@xiXinStudio LYPaymentField的最低版本还是默认的5.0，需要手动在podfile里用上述代码改成7.0或项目的最低支持系统版本都可以
